name: Unity Android Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unity-tests:
    runs-on: windows-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Run Unity Unit Tests using Unity Test Runner
    - name: Run Unity Unit Tests
      uses: game-ci/unity-test-runner@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        testMode: editmode
        unityVersion: 2022.3.30f1
        artifactsPath: test-results
    - name: Store Test Results
      uses: game-ci/unity-test-runner@v4
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
